name: code_text_field
description: A customizable code field supporting syntax highlighting, bi-directionnal scrolling and code modifiers
version: 1.1.0
homepage: https://github.com/BertrandBev/code_field

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller:
  highlight:
  flutter_highlight:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
